const palette = [
  { value: 'DEFAULT', name: 'DEFAULT', color: '#000000' },
  { value: 'CRIMSON', name: 'CRIMSON', color: '#DC143C' },
  { value: 'AMBER', name: 'AMBER', color: '#FFBF00' },
  { value: 'BLUE', name: 'BLUE', color: '#0000FF' },
  { value: 'LIME', name: 'LIME', color: '#00FF00' },
  { value: 'ORANGE', name: 'ORANGE', color: '#FFA500' },
  { value: 'SAND', name: 'SAND', color: '#C2B280' },
  { value: 'TEAL', name: 'TEAL', color: '#008080' },
  { value: 'VIOLET', name: 'VIOLET', color: '#8A2BE2' },
]

export const codeColInfo = [
  {
    accessorKey: 'order',
    header: '순서',
    size: '30',
    visible: '1',
    type: 'Int',
    canedit: 1, // 순서 값은 사용자가 수정할 수 없도록 설정
  },
  {
    accessorKey: 'codeGroupUid',
    header: '그룹코드UID',
    visible: '0',
    size: '60',
    type: 'Text',
    canedit: 1,
  },
  {
    accessorKey: 'codeUid',
    header: '코드 ID',
    visible: '1',
    size: '60',
    type: 'Text',
    canedit: 1,
  },
  {
    accessorKey: 'codeColor',
    header: '색상',
    visible: '1',
    size: '60',
    type: 'Enum',
    canedit: 1,
    option: palette,
  },
  {
    accessorKey: 'codeValue',
    header: '기본 코드값',
    visible: '1',
    size: '60',
    type: 'Text',
    canedit: 1,
  },
  {
    accessorKey: 'codeReferenceValue',
    header: '참조값',
    visible: '1',
    size: '60',
    type: 'Text',
    canedit: 1,
  },
  {
    accessorKey: 'isEditable',
    header: '사용여부',
    visible: '1',
    size: '60',
    type: 'Bool',
    canedit: 1,
  },
  {
    accessorKey: 'isEnabled',
    header: '수정 가능여부',
    visible: '1',
    size: '60',
    type: 'Bool',
    canedit: 1,
  },
]
