export const GroupColInfo = [
  {
    accessorKey: 'codeGroupUid',
    header: '코드그룹ID',
    visible: '1',
    size: '60',
    type: 'Text',
    canedit: 0,
  },
  {
    accessorKey: 'codeGroupName',
    header: '코드그룹명',
    visible: '1',
    size: '50',
    type: 'Text',
    canedit: 1,
  },
  {
    accessorKey: 'codeGroupDescription',
    header: '코드그룹 설명',
    visible: '1',
    size: '80',
    type: 'Text',
    canedit: 1,
  },
  {
    accessorKey: 'codeGroupReferenceValue',
    header: '참조값',
    visible: '1',
    size: '60',
    type: 'Text',
    canedit: 1,
  },
  {
    accessorKey: 'majorCategory',
    header: '대분류',
    visible: '1',
    size: '45',
    type: 'Text',
    canedit: 1,
  },
  {
    accessorKey: 'middleCategory',
    header: '중분류',
    visible: '1',
    size: '45',
    type: 'Text',
    canedit: 1,
  },
  {
    accessorKey: 'minorCategory',
    header: '소분류',
    visible: '1',
    size: '45',
    type: 'Text',
    canedit: 1,
  },
  {
    accessorKey: 'isEditable',
    header: '사용여부',
    visible: '1',
    size: '60',
    type: 'Bool',
    canedit: 1,
  },
]
